name: ChestLocking
version: ${project.version}
main: com.seailz.chestlock.ChestLockingPlugin
authors: [ Seailz ]
description: Adds the ability to lock chests
api-version: 1.13
website: www.seailz.com
